baseURL = 'https://jakobschumacher.github.io/praxisbeispiel/'
languageCode = 'de-DE'
title = 'Gynäkologische Praxis Musterfrau'

[params]
  # Praxis-Stammdaten (zentral an einer Stelle)
  praxisname = "Gynäkologische Praxis Musterfrau"
  inhaberin = "Dr. med. Erika Musterfrau"
  strasse = "Musterstraße 123"
  plz = "12345"
  ort = "Berlin"
  telefon = "030 123 456 78"
  email = "praxis@beispiel.de"

  # Öffnungszeiten
  [params.oeffnungszeiten]
    montag = "08:00 - 12:00 und 14:00 - 18:00 Uhr"
    dienstag = "08:00 - 12:00 und 14:00 - 18:00 Uhr"
    mittwoch = "08:00 - 12:00 Uhr"
    donnerstag = "08:00 - 12:00 und 14:00 - 18:00 Uhr"
    freitag = "08:00 - 12:00 Uhr"
    samstag = "Geschlossen"
    sonntag = "Geschlossen"

[menu]
  [[menu.main]]
    name = "Startseite"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 2
  [[menu.main]]
    name = "Leistungen"
    url = "/leistungen/"
    weight = 3
  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 4
  [[menu.main]]
    name = "Impressum"
    url = "/impressum/"
    weight = 5
  [[menu.main]]
    name = "Datenschutz"
    url = "/datenschutz/"
    weight = 6
