name: Hugo Website auf GitHub Pages deployen

on:
  # Wird bei jedem Push auf main ausgeführt
  push:
    branches:
      - main
  # Ermöglicht manuelles Auslösen des Workflows
  workflow_dispatch:

# Setzt Berechtigungen für das GITHUB_TOKEN, um Deployment auf GitHub Pages zu erlauben
permissions:
  contents: read
  pages: write
  id-token: write

# Erlaubt nur einen gleichzeitigen Deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Standard-Shell für alle Schritte
defaults:
  run:
    shell: bash

jobs:
  # Build-Job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.0
    steps:
      - name: Hugo installieren
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: GitHub Pages konfigurieren
        id: pages
        uses: actions/configure-pages@v4

      - name: Hugo-Website bauen
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Build-Artefakt hochladen
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment-Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Auf GitHub Pages deployen
        id: deployment
        uses: actions/deploy-pages@v4
