name: Quarto Website auf GitHub Pages deployen

on:
  # Wird bei jedem Push auf main ausgeführt
  push:
    branches:
      - main
  # Ermöglicht manuelles Auslösen des Workflows
  workflow_dispatch:

# Setzt Berechtigungen für das GITHUB_TOKEN, um Deployment auf GitHub Pages zu erlauben
permissions:
  contents: read
  pages: write
  id-token: write

# Erlaubt nur einen gleichzeitigen Deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Quarto installieren
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.550

      - name: GitHub Pages konfigurieren
        uses: actions/configure-pages@v4

      - name: Quarto-Website rendern
        run: quarto render

      - name: Build-Artefakt hochladen
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Auf GitHub Pages deployen
        id: deployment
        uses: actions/deploy-pages@v4
